name: PlanetFxScreenbox
version: 1.1
author: Sebastian Mikolai

main: de.SebastianMikolai.PlanetFx.Screenbox.Screenbox

commands:
  sb:
    description: PlanetFxScreenbox Commands
    usage: /sb